/**
 * contourSvgExporter.ts
 * Translates extracted contours from contour_tracer.c into clean, normalized SVG path elements
 * suitable for architectural CAD editing and vector downloads.
 */

export interface ContourPoint {
  x: number;
  y: number;
}

export type ContourPolygon = ContourPoint[];

export interface SvgExportOptions {
  strokeColor?: string;
  strokeWidth?: number;
  fillColor?: string;
  normalize?: boolean; // If true, normalizes coordinates to [0, 1] relative to width/height
  precision?: number;  // Decimal places for points (default 2)
  includeMetadata?: boolean;
}

/**
 * Converts an array of contour polygons (as traced by contour_tracer.c) into normalized SVG path strings.
 * Example: "M 10 10 L 100 10 L 100 100 Z"
 */
export function contourToSvgPathData(
  polygon: ContourPolygon,
  width: number,
  height: number,
  options: SvgExportOptions = {}
): string {
  if (!polygon || polygon.length === 0) {
    return "";
  }

  const { normalize = false, precision = 2 } = options;
  const scaleX = normalize && width > 0 ? 1 / width : 1;
  const scaleY = normalize && height > 0 ? 1 / height : 1;

  const formatCoord = (val: number, scale: number): string => {
    const scaled = val * scale;
    return Number(scaled.toFixed(precision)).toString();
  };

  const commands = polygon.map((pt, idx) => {
    const xStr = formatCoord(pt.x, scaleX);
    const yStr = formatCoord(pt.y, scaleY);
    return idx === 0 ? `M ${xStr} ${yStr}` : `L ${xStr} ${yStr}`;
  });

  return `${commands.join(" ")} Z`;
}

/**
 * Generates a complete standalone SVG document containing extracted floor plan contours.
 */
export function generateFloorplanSvg(
  contours: ContourPolygon[],
  width: number,
  height: number,
  venueId: string = "venue",
  options: SvgExportOptions = {}
): string {
  const {
    strokeColor = "#0284c7",
    strokeWidth = 2,
    fillColor = "rgba(14, 165, 233, 0.15)",
    includeMetadata = true,
  } = options;

  const viewBoxWidth = width > 0 ? width : 800;
  const viewBoxHeight = height > 0 ? height : 600;

  const pathElements = contours
    .map((contour, index) => {
      const d = contourToSvgPathData(contour, viewBoxWidth, viewBoxHeight, options);
      if (!d) return "";
      return `    <path id="contour-${index + 1}" d="${d}" fill="${fillColor}" stroke="${strokeColor}" stroke-width="${strokeWidth}" stroke-linejoin="round" stroke-linecap="round" />`;
    })
    .filter(Boolean)
    .join("\n");

  const metadataComment = includeMetadata
    ? `  <!-- Generated by WorkSphere Floor Plan Vectorizer (contour_tracer.c) -->\n  <!-- Venue: ${venueId} | Contours: ${contours.length} | ViewBox: 0 0 ${viewBoxWidth} ${viewBoxHeight} -->\n`
    : "";

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${viewBoxWidth} ${viewBoxHeight}" width="${viewBoxWidth}" height="${viewBoxHeight}">
${metadataComment}  <g id="floorplan-contours" class="architectural-contours">
${pathElements}
  </g>
</svg>`;
}

/**
 * Triggers client-side download of the generated SVG vector file.
 * The file is named `[venueId]-floorplan-vector.svg`.
 */
export function downloadFloorplanSvg(
  contours: ContourPolygon[],
  width: number,
  height: number,
  venueId: string = "venue",
  options: SvgExportOptions = {}
): string {
  const sanitizedVenueId = venueId.replace(/[^a-zA-Z0-9_-]/g, "_") || "venue";
  const filename = `${sanitizedVenueId}-floorplan-vector.svg`;
  const svgContent = generateFloorplanSvg(contours, width, height, sanitizedVenueId, options);

  if (typeof window !== "undefined" && typeof document !== "undefined") {
    const blob = new Blob([svgContent], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }

  return filename;
}
